= ljuv Documentation
:toc: left
:sectanchors:

https://github.com/ImagicTheCat/ljuv[*ljuv*] is a Lua library built on https://libuv.org/[libuv] and https://luajit.org/[LuaJIT] 2.1 (HEAD).

A main event loop combined with coroutines can be a way to nicely parallelize and synchronize various operations, which is what computing is mostly about.

Not only a binding to *libuv*, the library aims to expose different levels of abstraction and address problems like multi-threading.

== Error handling

=== Callbacks

Errors from loop callbacks are properly handled; they will be deferred, queued and propagated by `loop:run()` as soon as possible (after a call to `loop:stop()`). After an error, the state of the loop is still valid and `loop:run()` can be called again to propagate the next error or to continue execution.

NOTE: In most cases catching errors from `loop:run()`, the root of the application, is not meaningful and it should probably be done at the callback level instead.

== Resources management

=== Loop and handles

Handles are created and owned by a loop, they are not garbage collected on their own. To release an handle and its resources, `handle:close()` must be called. A loop will close its handles when garbage collected.

WARNING: Because of the design of *ljuv*, if an handle callback is an anchor for the associated loop, e.g. it has a reference to it directly or indirectly by its upvalues, the loop will not be garbage collected until the VM is closed. For most applications it doesn't matter because they will probably use the default global loop as their main event loop.

Although *ljuv* uses *cdata* objects, care is taken to preserve their identity in the API. When an handle is passed to a callback it will be the same *cdata* object returned by the loop. That *cdata* object identifies the handle and can be used as a key.

=== Shared objects

Objects like *channels* or *shared flags* are properly managed from multiple threads by the use of reference counting (if correctly exported/imported).

An *async* handle exported to another thread will act more as a weak reference: it will check for the validity of the handle before attempting an operation.

== API Reference
