= Thread API

== ljuv.new_shared_flag(value [, final_value])

Create a shared flag.

value:: integer (C `int`)
final_value:: same as _value_, but set at finalization

== shared_flag:set(value)

Set the shared flag's value.

value:: integer (C `int`)

== shared_flag:get()

Returns the shared flag's value.

== ljuv.new_channel()

Create a channel.

== channel:push(...)

Push a message.

...:: payload arguments

== channel:pull()

Pull a message (blocking).

Returns payload arguments.

== channel:try_pull()

Pull a message (non-blocking).

Returns a boolean status, *true* followed by the payload arguments if a message has been pulled, or *false* otherwise.

== channel:count()

Count the number of pending messages.

== ljuv.new_thread(func, ...)

Create a thread.

The created Lua state inherits from the current values of `package.path` and `package.cpath`.

It attempts to export each argument which allows, for example, to pass a channel without manual calls to export/import.

Nothing will be done about the function's upvalues as it would be semantically incorrect to transfer them (a Lua upvalue is a reference to an outer local, not just a value).

The function's return values, encoded by String Buffers, will be returned by <<thread-join>> on successful completion.

func:: thread entry function, a Lua function or a string of Lua code/bytecode
...:: arguments passed to the function, must be encodable by String Buffers

== thread:running()

Check if the thread is still running. The thread is marked as running at creation and the flag is set to *false* at the end of its execution.

TIP: This is a general convenient implementation. More specific detection mechanisms, e.g. using an *async* handle, may be implemented from the entry function.

Returns a boolean.

[#thread-join]
== thread:join()

Join the thread (blocking).

Thread objects are not subject to automatic memory management; this function must be called to gracefully wait for the thread to complete and release its resources.

Returns a boolean status, *true* followed by the thread function return values on successful completion, or *false* followed by an error traceback on failure.
